### ISSUE TITLE
Please update to Mupen64Plus v2.5

### ISSUE THREAD

**Issue by pizuz** [OpenEmu/Mupen64Plus-Core#9]
Hi,

apparently there's this, now:

https://github.com/mupen64plus/mupen64plus-core/releases/tag/2.5

Which fixes a lot of stuff and is a lot faster, too.

I'd love to see it in OpenEmu.

Regards,
pizuz

**Comment by clobber** [comment]
You registered to post this :|

Anyway, our port has the majority of those changes already. We'll push out a new version with the rest later. In order to manage your expectations, you should expect very few compatibility changes in the games, especially because our port still uses the Rice GPU plugin.

**Comment by pizuz** [comment]
Yeah, sure, why not?

I simply didn’t know whether or not you had this on your radar and wanted to make sure you did. And registering on GitHub in order to nag devs is what GitHub is for, isn’t it? :P

Anyway, thanks for the quick response.

Regards,
pizuz

**Comment by adamcoomes** [comment]
I've tested mupen64plus 2.5 outside of openemu and noticed a solid improvement on several games with the rice plugin. Looking forward to this update as well!
